logo: "/jiri-svoboda-avatar.jpg"
title: "ğŸ–¥ï¸ ğŸ‡¨ğŸ‡¿ ğŸ€"
description: "Enthusiastic fullstack web developer using Next.js, React.js and ReactNative"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
